#!/usr/bin/python

from subprocess import check_output, CalledProcessError
import json
import sys
import fileinput

#######################
# Constants
APIKEY = ""
FPURL = "https://www.filepicker.io"
FPAPIURL = "https://developers.filepicker.io"

#######################
# Make sure we have curl
try:
    check_output('curl --help > /dev/null', shell=True)
except CalledProcessError:
    exit("`curl` is requrired. Please install it")

#######################
# Find or register for an Filepicker.io account
if not APIKEY:
    email = ''
    while not email:
        email = raw_input('Enter your email for a filepicker.io acccount: ')

    # pretty sure this isn't public. found it by looking at the jotform integration
    APIKEY = check_output(['curl', '--silent', "%(fpurl)s/getKey?email=%(email)s" % {'fpurl': FPAPIURL, 'email': email}])

    #######################
    # Modify the file, if you can, so that it contains the apikey
    try:
        for line in fileinput.input(sys.argv[0], inplace=1):
            line = line.rstrip()
            if line == 'APIKEY = ""':
                print 'APIKEY = "%s"' % (APIKEY)
            else:
                print line
    except Exception:
        pass

#######################
# Usage if no right number of args
if len(sys.argv) != 2:
    print "usage: filepicker <filename>"
    exit()

#######################
# Upload the file
output = check_output('curl -F "fileUpload=@%(filename)s" -F "apikey=%(apikey)s" %(fpurl)s/api/path/storage/%(filename)s' %
        {"filename": sys.argv[1], "apikey": APIKEY, "fpurl": FPURL}, shell=True)
data = json.loads(output)
url = data['data'][0]['url']
print url

#######################
# Copy to the clipboard
try:
    if sys.platform == 'darwin':
        check_output('echo "%s" | pbcopy' % (url), shell=True)
    elif sys.platform == 'linux2':
        try:
            check_output('echo "%s" | xclip -selection clipboard > /dev/null 2>&1' % (url), shell=True)
        except CalledProcessError:
            try:
                check_output('echo "%s" | xsel -b -i > /dev/null 2>&1' % (url), shell=True)
            except CalledProcessError:
                pass
except Exception:
    pass
        
